// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAifCcTbl3Xkcli5NwfWs0Etkaie8kVy9I',
    appId: '1:88831933476:web:4d99a225b4075f4b4bacb1',
    messagingSenderId: '88831933476',
    projectId: 'myfirstflutterappjourney',
    authDomain: 'myfirstflutterappjourney.firebaseapp.com',
    storageBucket: 'myfirstflutterappjourney.firebasestorage.app',
    measurementId: 'G-BX58PYZFE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzCFnzAux_6QNIOaDGwciFCgBNSgOyQVs',
    appId: '1:88831933476:android:2cae12126bb803944bacb1',
    messagingSenderId: '88831933476',
    projectId: 'myfirstflutterappjourney',
    storageBucket: 'myfirstflutterappjourney.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxL6BQLkqZgchCV-TeXlk7ryDiIWGwm7A',
    appId: '1:88831933476:ios:0e27f2f1b10c73e44bacb1',
    messagingSenderId: '88831933476',
    projectId: 'myfirstflutterappjourney',
    storageBucket: 'myfirstflutterappjourney.firebasestorage.app',
    iosBundleId: 'com.example.myFirstFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxL6BQLkqZgchCV-TeXlk7ryDiIWGwm7A',
    appId: '1:88831933476:ios:0e27f2f1b10c73e44bacb1',
    messagingSenderId: '88831933476',
    projectId: 'myfirstflutterappjourney',
    storageBucket: 'myfirstflutterappjourney.firebasestorage.app',
    iosBundleId: 'com.example.myFirstFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAifCcTbl3Xkcli5NwfWs0Etkaie8kVy9I',
    appId: '1:88831933476:web:c52a87e25bd931b44bacb1',
    messagingSenderId: '88831933476',
    projectId: 'myfirstflutterappjourney',
    authDomain: 'myfirstflutterappjourney.firebaseapp.com',
    storageBucket: 'myfirstflutterappjourney.firebasestorage.app',
    measurementId: 'G-5RC6DSHQ8S',
  );

}